# Generated by Django 6.1 on 2026-08-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abot',
            new_name='About',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='abot_description',
            new_name='about_description',
        ),
    ]
